# Generated by Django 2.2.6 on 2019-10-30 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('postal_index', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderpic', to='map_generator.Starmap')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderpdf', to='map_generator.Starmap')),
            ],
        ),
    ]
